### ISSUE TITLE
Add iCal feed

### ISSUE THREAD

**Issue by willdurand** [clermontech/planet#49]

**Comment by lapsus63** [comment]
En attendant de pouvoir faire un truc automatique (en Ruby ?) j'ai commencé à agréger les derniers événements de Planet Clermont'ech dans un agenda partageable :
- https://calendar.google.com/calendar?cid=bTdnZGlxbmRwaHI0MzN0NjdpdjBpN2Nxam9AZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ

Pour ceux qui connaissent Ruby, j'ai trouvé une doc qui semble détaillée et qui permettrait de convertir les événements dans les /posts/ au format iCal à l'aide d'un petit script à écrire.
- https://developers.google.com/calendar/quickstart/ruby

**Comment by willdurand** [comment]
On supporte déja iCal pour chaque évènement. Il suffirait de reprendre la partie "iCal" dans `_includes/event.yml` (de mémoire) et créer un fichier similaire à `atom.xml` (`planet.ical` par exemple) pour lister tous les évènements et les formater en iCal. On ne devrait pas avoir besoin de Ruby.

**Comment by lapsus63** [comment]
Hello, j'ai fait une pull request pour rajouter le lien vers un ical généré par un script bash.
Je n'ai pas trouvé par quel processus était regénéré le fichier atom.xml par contre ?

**Comment by krichprollsch** [comment]
Done via https://github.com/clermontech/planet/blob/main/themes/hyde-custom/layouts/_default/home.calendar.ics
